package main

import (
	"fmt"
	"os"
)

// runCompletion prints a shell completion script to stdout. Only zsh is
// supported; the script is hand-written because the stdlib flag package has
// no completion support and flowlog takes no dependencies.
func runCompletion(args []string) int {
	if len(args) != 1 || args[0] != "zsh" {
		fmt.Fprintln(os.Stderr, "usage: flowlog completion zsh")
		fmt.Fprintln(os.Stderr, "Install:")
		fmt.Fprintln(os.Stderr, "  mkdir -p ~/.zfunc && flowlog completion zsh > ~/.zfunc/_flowlog")
		fmt.Fprintln(os.Stderr, "  # in ~/.zshrc, before compinit:")
		fmt.Fprintln(os.Stderr, "  fpath=(~/.zfunc $fpath)")
		return 1
	}
	fmt.Print(zshCompletion)
	return 0
}

const zshCompletion = `#compdef flowlog

# Generated by "flowlog completion zsh". Regenerate after upgrading flowlog.

_flowlog_profiles() {
  local -a profs
  profs=(${(f)"$(flowlog profiles 2>/dev/null | sed -n 's/^  \([^ ]*\) - .*/\1/p')"})
  _describe -t profiles 'profile' profs
}

_flowlog_services() {
  local cfg=${FLOWLOG_CONFIG:-$HOME/dev-services.json}
  local -a svcs
  svcs=(${(f)"$(sed -n 's/.*\"name\": *\"\([^\"]*\)\".*/\1/p' "$cfg" 2>/dev/null)"})
  _describe -t services 'service' svcs
}

_flowlog() {
  local -a subcmds
  subcmds=(
    'start:launch services in a tmux session, one window each'
    'attach:attach to the tmux session created by start'
    'profiles:list, add, or remove service profiles'
    'doctor:check the local dev environment, read-only'
    'setup:run the doctor checks and repair what can be repaired'
    'completion:print the zsh completion script'
  )

  case $words[2] in
    start)
      _arguments \
        '(-p --profile)'{-p,--profile}'[use a named profile, skip the interactive picker]:profile:_flowlog_profiles' \
        '--skip-aws-check[skip the AWS SSO credential check]' \
        '--debug[verbose output for the AWS credential check]'
      ;;
    attach)
      _arguments \
        '(-s --session-name)'{-s,--session-name}'[tmux session name (default dev-services)]:session name:'
      ;;
    profiles)
      if (( CURRENT == 3 )); then
        local -a verbs
        verbs=(
          'add:create a profile (interactive picker without -s)'
          'remove:delete a profile'
        )
        _describe -t actions 'action' verbs
      elif [[ $words[3] == add ]]; then
        _arguments \
          '-s[comma-separated service names or aliases]:services:_flowlog_services' \
          '-d[profile description]:description:' \
          '--force[overwrite an existing profile with this name]'
      elif [[ $words[3] == remove ]]; then
        (( CURRENT == 4 )) && _flowlog_profiles
      fi
      ;;
    doctor|setup)
      _arguments \
        '--os-url[OpenSearch base URL (default http://localhost:9200)]:url:' \
        '--osd-url[Dashboards base URL (default http://localhost:5601)]:url:' \
        '--index[index prefix / saved object id (default flowlog)]:name:'
      ;;
    completion)
      (( CURRENT == 3 )) && _values 'shell' 'zsh[print zsh completion script]'
      ;;
    *)
      # Default mode: offer subcommands in position 2, plus the tail-mode flags.
      (( CURRENT == 2 )) && _describe -t subcommands 'subcommand' subcmds
      _arguments \
        '-f[follow live from EOF instead of a post-hoc scan]' \
        '--op[keep only entries with this operation id]:operation id:' \
        '--since[post-hoc scan window before now, e.g. 30m, 24h (default 1h)]:duration:' \
        '--level[comma-separated levels to include]:levels:(error warn info verbose silly debug)' \
        '--profile[service profile from dev-services.json]:profile:_flowlog_profiles' \
        '--services[comma-separated service names or aliases]:services:_flowlog_services' \
        '--ship[also ship entries to OpenSearch]' \
        '--os-url[OpenSearch base URL (default http://localhost:9200)]:url:' \
        '--index[index prefix, docs go to daily <prefix>-YYYY.MM.DD indices]:name:' \
        '--retain[with --ship: delete daily indices older than this many days, 0 = keep forever (default 7)]:days:' \
        '--no-color[disable ANSI color]'
      ;;
  esac
}

_flowlog "$@"
`
